steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.production'
      - '-t'
      - 'gcr.io/startologer-ai/startologer-app'
      - '.'
images:
  - 'gcr.io/startologer-ai/startologer-app'
timeout: '1800s'
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
