# Cloud Build configuration for StartupEval AI with ADK
# Builds and deploys to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/startulogger-adk:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/startulogger-adk:latest'
      - './project-root/backend/real_adk'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/startulogger-adk:$SHORT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'startulogger-adk'
      - '--image'
      - 'gcr.io/$PROJECT_ID/startulogger-adk:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,ADK_MODEL_NAME=gemini-2.0-flash'
      - '--set-secrets'
      - 'GEMINI_API_KEY=gemini-api-key:latest,DOCUMENTAI_PROCESSOR_ID=documentai-processor-id:latest,GOOGLE_APPLICATION_CREDENTIALS=/secrets/service-account-key'

images:
  - 'gcr.io/$PROJECT_ID/startulogger-adk:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/startulogger-adk:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
